export const linkedinURL = 'https://www.linkedin.com/in/hernanarevalo'
export const githubURL = 'https://www.instagram.com/nan.arevalo'
export const instagramURL = 'https://www.instagram.com/nan.arevalo'
export const whatsappURL = 'https://wa.me/+543516148912'
export const phone = '+54 351 6148912' 
export const email = 'hernanarevalo16@gmail.com' 
export const curriculumURL = 'https://drive.google.com/file/d/1QAsdgUDvDbA2dRTpuGj9ABvY1UoAPM8v/view?usp=sharing'